[tool.isort]
profile="black"
line_length=119
known_django="django"
known_first_party="crispy_forms"
sections="FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"

[tool.black]
line-length = 119
target-version = ['py36']
include = '(crispy_forms)\/(.+)(py?$)'
